services:
  ros2_eval_task:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # keep stdin open
    user: dev # run the container as the ubuntu user
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.Xauthority
      - QT_X11_NO_MITSHM=1
      - PYTHONPATH=/opt/ros/humble/lib/python3.12/site-packages
      - /dev:/dev # share the devices with the host
      - /dev/shm:/dev/shm # share the shared memory with the host
    volumes:
      - ../ros2_eval_task:/home/dev/ros2_ws/src/ros2_eval_task:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # share the X11 socket with the host
      - ~/.Xauthority:/root/.Xauthority # share the Xauthority file with the host
    container_name: ros2_gz_gui # name of the container that will be created
